[database]
host = "localhost"
port = "3306"
user = "munzir"
password = "munzirdev"
name = "studs"


[googleLogin]
clientID = "414470856146-tjhu1r3krc1tf3pfdduf4hdteuo32d1u.apps.googleusercontent.com"
clientSecret = "9IhRhPCmTZo8JvgnWXtuDBGv"
